### PR TITLE
Fix - Make `values` a list of list, allowing to load fields with commas

### LINKED ISSUE #170: Issue with loading data from the graph when columns have a `,` (including the JSON string)
Debugging the integration tests failure made me realize that there is some issue/limitation around how we load data for connectors that don't support the `values('a', 'b', 'c')` approach. 

Fixing it will require some decent refactor.

Currently, we are saving the "rows" of data to load as a list of string and do the following processing:
- for Postgres/Snowflake, we load it "as-is" by wrapping the string with parenthesis: `('a', 'b', 'c')`
- for the other ones, we split reach row into individual column, using `value.split(',')`. While this works when no field has a `,` in it, it is actually failing if a field has one (like a JSON string with multiple keys).

I think that we should actually save the different rows as a list of lists rather than a list of strings but this requires a change to all the `get_` macros as well as `select_from_values`.

I will raise another issue about this..

_Originally posted by @b-per in https://github.com/dbt-labs/dbt-project-evaluator/issues/169#issuecomment-1180119224_

### PR DESCRIPTION
**Pull request by b-per**
This is a:
- [x] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 

Closes #170

## Description & motivation

Changing the logic of the different ingestion macros and `select_from_values` to make values a list of lists. We used to have it as a list of strings and split by `,` for BigQuery and Redshift but it doesn't work if there is a `,` in a field, like `meta` or if we want to load a JSON string in a column.

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [x] BigQuery
    - [x] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

File: macros/unpack/get_exposures.sql [hunk 1]
```diff
@@ -11,21 +11,22 @@
...
-            '{{ node.maturity}}',
-            '{{ node.package_name }}',
-            '{{ node.url }}',
-            '{{ node.owner.name }}',
-            '{{ node.owner.email }}'
-
-          {% endset -%}
+          {%- set values_line = 
+            [
+              "'" ~ node.unique_id ~ "'",
```
Comment (dave-connors-3) [inline macros/unpack/get_exposures.sql:16]: is there any way for us to make this a little less repetitive? i recently learned about `adapter.quote` -- not sure it even works here but could be cool

File: macros/unpack/get_metrics.sql [hunk 2]
```diff
@@ -32,7 +19,26 @@
             {%- else -%}
                 ''
             {% endif -%}
-        {%- endset -%}
+          {% endset %}
+
+          {%- set values_line =
```
Comment (dave-connors-3) [inline macros/unpack/get_metrics.sql:24]: any reason to split these set blocks apart?

**Review by dave-connors-3 — APPROVED** [review]
🦞 -- this looks good, a few clarifying comments but I'm with you on the approach. You cannot merge until you review #132 😃

File: macros/unpack/get_exposures.sql (hunk 1 above)
Comment (b-per) [reply macros/unpack/get_exposures.sql:16]: I think that `adapter.quote` is targeted at quoting database object names (e.g. surrounding the db name with `` for BQ, etc...), which is different from how to quote strings.

I get your point though and will create a macro for this use case to make it clearer than using the complex pattern everywhere.

Comment (b-per) [reply macros/unpack/get_exposures.sql]: I have pushed a commit with a new macro

File: macros/unpack/get_metrics.sql (hunk 2 above)
Comment (b-per) [reply macros/unpack/get_metrics.sql:24]: Actually I can't get them together. I don't think I can use `if`s and `for`s within the variable definition itself.
